version: 2
jobs:
  build:
    docker:
      - image: 'cypress/base:10'
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'npm ci'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Build Project'
          command: 'npm run build'
      -run:
          name: 'Start Project'
          command: 'npm run start'
      - run:
          name: 'Test Project'
          command: 'npm run test'
      - run:
          name: 'Deploy to Firebase Hosting'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'
#   test:
#     docker:
#       - image: 'circleci/node:10'
#     steps:
#       - checkout
#       - run:
#           name: 'Test Project'
#           command: 'npm run test'
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build